### ISSUE TITLE
broken solutions

### ISSUE THREAD

**Issue by westwq** [MAD11877/mad22-practical-6---storage-HanXihe-NP#2]
https://github.com/MAD11877/mad22-practical-6---storage-HanXihe-NP/blob/fd675f7aae179b30ac6858555e811702844dee5e/app/src/main/java/com/np/madexercise2hanxihe/LoginActivity.java#L29-L65
you just hav to use the database read to do the login
dont hav to use firebase authentication

https://github.com/MAD11877/mad22-practical-6---storage-HanXihe-NP/blob/fd675f7aae179b30ac6858555e811702844dee5e/app/src/main/java/com/np/madexercise2hanxihe/ListActivity.java#L43-L60
this was juz a demo of how to link activity to db and what not to be done.
your database will keep growing each time it runs

**Comment by HanXihe** [comment]
Fixed with latest commit
